version: 0.0
os: linux
files:
  - source: /
    destination: /root/test_pipeline/
hooks:
  BeforeInstall:
    - localtion: deploy/before_install
      timeout: 300
      runas: root
  ApplicationStop:
    - location: deploy/application_stop
      timeout: 300
      runas: root
  ApplicationStart:
    - location: deploy/application_start
      timeout: 300
      runas: root

