version: 0.0
os: linux
files:
  - source: /time.py
    destination: /root/test_pipeline/
hooks:
  ApplicationStop:
    - location: deploy/application_stop.sh
      timeout: 300
      runas: root
  BeforeInstall:
    - localtion: deploy/before_install.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: deploy/application_start.sh
      timeout: 300
      runas: root

