version: 0.0
os: linux
files:
  - source: /time.py
    destination: /root/test_pipeline/
hooks:
  ApplicationStop:
    - location: deploy/application_stop
      timeout: 300
      runas: root
  ApplicationStart:
    - location: deploy/application_start
      timeout: 300
      runas: root

